name: dual_knights
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flame: ^1.22.0
  flame_tiled: ^1.21.1
  flame_audio: ^2.10.5
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  dio: ^5.7.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.2.3
  path_provider: ^2.0.13


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/Factions/Knights/Troops/Warrior/Blue/Warrior_Blue_Small.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tiles/
    - assets/images/Terrain/Ground/
    - assets/images/Texture/
    - assets/images/Factions/Knights/Troops/Warrior/Blue/
    - assets/images/Factions/Knights/Troops/Warrior/Red/
    - assets/images/Factions/Goblins/Troops/Barrel/Red/
    - assets/images/Factions/Goblins/Troops/Barrel/Blue/
    - assets/images/Factions/Knights/Troops/Dead/
    - assets/images/Effects/Explosion/
    - assets/images/Factions/Knights/Buildings/Tower/
    - assets/images/Deco/
    - assets/images/Terrain/Water/Foam/
    - assets/images/UI/Buttons/
    - assets/images/UI/Pointers/
    - assets/images/Factions/Knights/Buildings/Castle/
    - assets/images/Resources/Trees/
    - assets/images/Terrain/Bridge/
    - assets/images/Resources/Sheep/
    - assets/tiles/
    - assets/tiles/UI/
    - assets/images/UI/
    - assets/images/UI/Ribbons/
    - assets/images/UI/Banners/
    - assets/images/logo/
    - assets/images/Factions/Goblins/Troops/TNT/Red/
    - assets/images/Factions/Knights/Troops/Archer/Red/
    - assets/images/Factions/Goblins/Troops/Torch/Red/
    - assets/images/Factions/Knights/Troops/Pawn/Red/
    - assets/images/Factions/Knights/Troops/Archer/Blue/
    - assets/images/Factions/Knights/Buildings/House/House_Blue.png
    - assets/images/Resources/Gold Mine/GoldMine_Active.png
    - assets/images/Resources/Gold Mine/GoldMine_Destroyed.png
    - assets/images/Factions/Knights/Troops/Pawn/Blue/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png/Level/Star/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png/Star/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png@2x/Star/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png@2x/Level/Star/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png/Button/Square/Fill/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png/Buttons/Square/ArrowLeft-Thin/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png/Buttons/Square/ArrowRight-Bold/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png/Buttons/Square/ArrowLeft-Bold/
    - assets/images/Prinbles_Asset_Robin (v 1.1) (9_5_2023)/png/Icon/
    - assets/images/UI/Icons/
    - assets/images/Factions/Knights/Troops/Archer/Yellow/Archer_Yellow.png
    - assets/images/base_image/
    - assets/images/
    - assets/images/Terrain/Water/
    - assets/images/Treasure/
    - assets/images/clouds/
    - assets/images/Factions/Knights/Troops/Archer/Purple/
    - assets/images/Factions/Knights/Troops/Archer/Arrow/
    - assets/audio/
    - assets/images/Effects/Checkpoint/
    - assets/images/Resources/Resources/
    - assets/images/Deco/16.png
    - assets/images/Deco/17.png
    - assets/images/Deco/18.png
    - assets/images/Terrain/Ground/Shadows.png
    - assets/images/UI/Banners/Banner_Connection_Left.png
    - assets/images/UI/Banners/Banner_Connection_Right.png
    - assets/images/UI/Ribbons/Ribbon_Yellow_3Slides.png
    - assets/images/Factions/Knights/Troops/Warrior/Blue/Warrior_Blue_Big.png
    - assets/images/Factions/Knights/Troops/Warrior/Red/Warrior_Red_Big.png

    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: DualKnights
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
